---
title: "Data Descriptives"
author: "Maggie Nead"
date: "6/17/2020"
output: html_document
---

```{r setup, include = FALSE}
source(here::here("setup.R"))
source(here::here("dataSetup.R"))

```


```{r reorder}
#Reorder data

data %<>%
  select(bioname, yearelected, member_reelected, congress, TYPE, everything())

data %<>%
  filter(!is.na(TYPE))

```

#Histogram of observations in each congress
```{r hist}
data %>%
  with(hist(congress))
```



```{r typeTab}

data %>%
  with(table(TYPE)) %>%
  kable() %>%
  kable_styling()


```

```{r cong106}

data %>%
  filter(congress %in% 106) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()


```

```{r cong107}

data %>%
  filter(congress %in% 107) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()



```

```{r cong108}

data %>%
  filter(congress %in% 108) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()

```

```{r cong109}

data %>%
  filter(congress %in% 109) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()
```

```{r cong110}

data %>%
  filter(congress %in% 110) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()

```

```{r cong111}

data %>%
  filter(congress %in% 111) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()

```

```{r cong112}
data %>%
  filter(congress %in% 112) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()


```

```{r cong113}

data %>%
  filter(congress %in% 113) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()

```

```{r cong114}

data %>%
  filter(congress %in% 114) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()

```

```{r cong115}

data %>%
  filter(congress %in% 115) %>%
  with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
  kable() %>%
  kable_styling()

```


#Fix Me
```{r cong116}
# data %>%
#   filter(congress %in% 116) %>%
#   with(table(TYPE, party, member_reelected, yearelected, as.factor(agency))) %>%
#   kable() %>%
#   kable_styling()
```





