---
title: "Research Question Write Up"
author: "Maggie Nead"
date: "6/11/2020"
header-includes:
    - \usepackage{setspace}\doublespacing
output: html_document
---

# Research Question Write Up
    
### **Introduction:**   

Political scientists have long been studying factors which lead to reelection. Political ideology, campaign platforms, and voting records are just some of the topics that have been researched. Significant improvements have been made to the way in which researchers think about and study reelection but there is still gaps in what is known. One of the biggest gaps being what happens outside of public perview. Who do members of congress advocate for behind closed doors and what impact does that have on reelection? This research seeks to answer the question, what kinds of congressional correspondence behavior leads to reelection?
There may exist patterns and relationships between congressional correspondence and reelection. By determining what and who a member of congress advocates for and comparing that to whether or not they get reelected the data may show which priorities lead to reelection and which may lead a member to be replaced.

### **Purpose**  

A lot of research has been done in the past examining reelection. Political scientists often theorize what drives reelection. What causes incumbents to not be reelected? How do we predict who will be elected? What drives people to vote the way they do? These are also questions that have been studied in depth. This research often looks at voting records, party platforms, peeches on the campaign trail, political history, and even candidate scandals. This research seeks to look at something that has not be addressed, what about what happens behind the scenes? Due to the Freedom of Information Act correspodence sent by members of congress can become public knowledge but this is a lengthy process and so is not often invoked for research purposes. This research looks at correspondence gathered via the Freedom of Information Act to see if what members advocate for outside of the public spotlight has an effect on their reelection.
     
### **Data**  

All correspodence from a Member of Congress to a federal agency was requested. So far 383,824 letters have been collected and matched to the member it was sent from. This data was collected by the Correspondence Research project headed by Professor Powell at the University of Wisconsin-Madison. The data spans from the 106th to the 116th congress and was requested from every federal agency. The 383,824 observations we currently have contains the data from the federal agencies that have responded so far. Once collected the data was merged with the open source VoteView data. Voteview collects information on Members of Congress which included but is not limited to; names, congresses in which they served, chamber, state information, and ideology scores.  

1. The behavior of members who are reelected (i.e. in consecutive congresses)  
2. The behavior of members who are not reelected (i.e. not in consecutive congresses)  
3. Compared behavior between the members who did not run for reelection and those that lost their bid for reelection.
    
For the purposes of this research reelection will be defined as any member who is in consecutive congresses. Members who were not reelected shall be defined as any member who is in one congress and not the following congress. This research may further break this down between members who ran for reelection and lost and those who did not run for reelection at all.


### **Questions:**
  
The broad research question may be further broken down into the questions listed below:  

- Is the behavior between members who get reelected different from members who do not?  
  - How?
  
- Are members of congress not seeking reelection more willing to step outside of party lines on policy than those seeking reelection?
 
- Are corporate interests less important to members not seeking reelection?  
  - Or are members who do not advocate for corporate interests less likely to be reelected?  
    - Has this changed over time?
    
### **Why it is important**
    
### **Thesis**
   
###  **References**
Mayhew, David. 1974. Congress: The Electoral Connection. New Haven: Yale University Press.
