---
title: "Models"
author: "Maggie Nead"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
source(here::here("setup.R"))
source(here::here("dataSetup.R"))
```

```{r dataFilter, fig.height=3, fig.width=4}
d <- data %>%
  filter(!is.na(TYPE))

d %>%
group_by(TYPE) %>%
tally

d %<>%
  filter(TYPE == c(1,2,4))

d %<>%
  mutate(interest = ifelse(TYPE %in% c(1), "constituent", NA)) %>%
  mutate(interest = ifelse(TYPE %in% c(2,4), "corporate", interest))# %>%
  #mutate(interest = ifelse(! str_detect(TYPE, "1|2|4"), "neither", interest))



d %>%
  group_by(interest) %>%
  tally()

# d %>%
#   gather(interest,letters,FY1993:FY1998) %>%
#   spread(Field,value)


checkCounts <- d %>%
  count(bioname, icpsr, congress, reelections, party_name, interest, member_reelected, name = "lettersPerInterest")

d %<>%
  count(bioname, icpsr, congress, reelections, party_name, member_reelected, interest, name = "lettersPerInterest")
 
# 
# qplot(x = lettersPerInterest, y = reelections, facets = ~interest, data = d, na.rm = TRUE) +
#   geom_smooth(method = "lm")
 
qplot(x = lettersPerInterest, y = reelections, data = d, color = interest) +
  geom_smooth(method = "lm") 
  

d %<>% 
  spread(interest, lettersPerInterest)
 

 


# d %<>% 
#   mutate(corporateInterest = ifelse(str_detect(interest, "corporate"), lettersPerInterest, 0)) %>%
#   mutate(constituentInterest = ifelse(str_detect(interest, "constituent"), lettersPerInterest, 0))


```

```{r plots, fig.height=3, fig.width=4}
d %>%
  ggplot(aes(x=corporate, y=reelections)) + 
  geom_point(outlier.colour="black", outlier.shape=16,
               outlier.size=2, notch=TRUE) 

d %>%
  ggplot(aes(x=constituent, y=reelections)) + 
  geom_point(outlier.colour="black", outlier.shape=16,
               outlier.size=2, notch=TRUE) 


#d %<>% arrange(constituent) %>% kable(caption = "Legislators who wrote the most letters to FERC")

d %<>%
  filter(!str_detect(bioname, "McCAIN, John Sidney, III"))

d %>%
  ggplot(aes(x=corporate, y=reelections)) + 
  geom_point(outlier.colour="black", outlier.shape=16,
               outlier.size=2, notch=TRUE) 

d %>%
  ggplot(aes(x=constituent, y=reelections)) + 
  geom_point(outlier.colour="black", outlier.shape=16,
               outlier.size=2, notch=TRUE) 

# qplot(x = lettersPerInterest, y = reelections, data = d, color = interest) +
#   geom_smooth(method = "lm") 


```

```{r mplot}
 mplot <- function(m){m %>%
  tidy(conf.int = TRUE) %>%
    filter(term!="(Intercept)") %>%
ggplot() + 
  aes(x = term,
      y = estimate, 
      ymin = conf.low, 
      ymax = conf.high)+ 
    geom_hline(yintercept = 0, linetype =2) + 
  geom_pointrange() + coord_flip() }

```

#1 corporate, 2 constituent
```{r countModel1, fig.height=3, fig.width=4}
#d$interest <- ordered(d$interest, levels = c("neither", "corporate", "constituent"))

countModel <- glm(reelections ~ corporate + constituent, 
            data = d,  #%>% distinct(), 
            #contrasts = list(interest = contr.sum(2)),
         family = poisson)  

summary(countModel)

plot(countModel)

ggplot(countModel, aes(seq_along(.cooksd), .cooksd)) +
  geom_col()

countModel %>% mplot()+
  labs(x="", y="Increase in times reelection given letter interests")


```
Residual Deviance is greater than the degrees of freedom so we have over-dispersion.

```{r qpoisson, fig.height=3, fig.width=4}
library("MASS")
countModelq <- glm.nb(reelections ~ corporate + constituent, 
            data = d)  #%>% distinct(), 
            #contrasts = list(interest = contr.sum(2)),
         #link = log)  

summary(countModelq)

plot(countModelq)
ggplot(countModel, aes(seq_along(.cooksd), .cooksd)) +
  geom_col()

countModel %>% mplot()+
  labs(x="", y="Increase in times reelection given letter interests")


```

```{r countModel2, fig.height=3, fig.width=4}
countModelParty <- glm(reelections ~ corporate*party_name + constituent*party_name, 
            data = d,  #%>% distinct(), 
            #contrasts = list(interest = contr.sum(2)),
         family = poisson)  

summary(countModelParty)

plot(countModelParty)

countModelParty %>% mplot()+
  labs(x="", y="Increase in times reelection given letter interests and party")
```


```{r countModel2q, fig.height=3, fig.width=4}
countModelPartyq <- glm(reelections ~ corporate*party_name + constituent*party_name, 
            data = d,  #%>% distinct(), 
            #contrasts = list(interest = contr.sum(2)),
         family = quasipoisson)  

summary(countModelPartyq)

plot(countModelPartyq)

countModelParty %>% mplot()+
  labs(x="", y="Increase in times reelection given letter interests and party")
```

```{r logitmodel}

model <- glm(member_reelected ~ corporate + constituent, 
             data=d, 
             family=binomial(link="logit"))
summary(model)




```












